CREATE TABLE SESSION
(
    SESSION_ID    UUID PRIMARY KEY,
    FK_TOPIC_ID   UUID        NOT NULL FOREIGN KEY REFERENCES TOPIC(TOPIC_ID),
    SESSION_DATE  DATE        NOT NULL,
    SESSION_TIME  TIME        NOT NULL,
    LOCATION      VARCHAR(20) NOT NULL,
    REMARKS       TEXT,
    STATUS        VARCHAR(20) NOT NULL,
    FK_COACH_ID   UUID        NOT NULL FOREIGN KEY REFERENCES USERS(ID),
    FK_COACHEE_ID UUID        NOT NULL FOREIGN KEY REFERENCES USERS(ID)

)