CREATE TABLE USERS (
    ID UUID PRIMARY KEY,
    FIRST_NAME VARCHAR(25) NOT NULL,
    LAST_NAME VARCHAR(25) NOT NULL,
    EMAIL VARCHAR(40) UNIQUE NOT NULL,
    TEAM VARCHAR(40) NOT NULL,
    IS_COACH BOOLEAN DEFAULT FALSE
)