CREATE TABLE TOPIC (
    TOPIC_ID UUID PRIMARY KEY,
    TOPIC_NAME VARCHAR(25) NOT NULL
);

CREATE TABLE COACH_INFO_TOPIC (
    COACH_INFO_ID UUID NOT NULL,
    TOPIC_ID UUID NOT NULL,
    EXPERTISE VARCHAR(20) NOT NULL,
    FOREIGN KEY (COACH_INFO_ID) REFERENCES COACH_INFO(COACH_INFO_ID),
    FOREIGN KEY (TOPIC_ID) REFERENCES TOPIC(TOPIC_ID)
);